name: Update README with Latest Medium Articles

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch latest Medium articles
        run: |
          # Fetch the latest articles from Medium RSS feed
          curl -s https://medium.com/feed/@hajiafridbaba | \
          grep -o '<title>[^<]*</title>' | \
          sed 's/<\/\?title>//g' | \
          head -n 5 > latest_articles.txt

      - name: Prepare new section for README
        run: |
          # Prepare the new section for the README
          echo "## Latest Stories from My Mind 🧠" > new_section.md
          echo "" >> new_section.md
          echo "_This section is dynamically updated with my latest Medium articles._" >> new_section.md
          echo "" >> new_section.md
          while IFS= read -r line; do
            # Convert titles to URLs
            article_url=$(echo "$line" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | sed 's/[^a-z0-9-]//g')
            echo "- [$line](https://medium.com/@hajiafridbaba/$article_url)" >> new_section.md
          done < latest_articles.txt

          # Append the new section to the README
          cat new_section.md >> README.md
          rm new_section.md

      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add README.md
          git commit -m "Update README with latest Medium articles"
          git push
